version = 0.1
[dev]
[dev.deploy]
[dev.deploy.parameters]
stack_name = "bav-cri-api-1872"
s3_prefix = "bav-cri-api-1872"
region = "eu-west-2"
confirm_changeset = false
capabilities = "CAPABILITY_IAM CAPABILITY_NAMED_IAM"
parameter_overrides = "CodeSigningConfigArn=\"none\" Environment=\"dev\" PermissionsBoundary=\"none\" SecretPrefix=\"none\" VpcStackName=\"vpc-cri\" L2DynamoStackName=\"bav-cri-ddb\" L2KMSStackName=\"bav-cri-kms\""
image_repositories = []
